# Generated by Django 2.1.3 on 2019-10-22 03:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('w2r', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tiempo_10k',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tiempo_15k',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tiempo_21k',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tiempo_42k',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tiempo_5k',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
