# Generated by Django 2.1.3 on 2019-11-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w2r', '0002_auto_20191021_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='apellido_materno',
            new_name='apellidos',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='apellido_paterno',
        ),
        migrations.AddField(
            model_name='registro',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='peso_kgs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
