# Generated by Django 2.1.3 on 2019-11-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w2r', '0005_registro_confirmado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='tiempo_15k',
        ),
        migrations.AlterField(
            model_name='registro',
            name='confirmado',
            field=models.BooleanField(verbose_name='Acepto'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tiempo_10k',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tiempo_21k',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tiempo_42k',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tiempo_5k',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
