# Generated by Django 2.1.3 on 2018-11-19 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'club',
                'verbose_name_plural': 'clubes',
            },
        ),
        migrations.CreateModel(
            name='Corredor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('apellido_paterno', models.CharField(max_length=300)),
                ('apellido_materno', models.CharField(max_length=300)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(max_length=254)),
                ('originario_nuevo_laredo', models.BooleanField()),
                ('residente_nuevo_laredo', models.BooleanField()),
                ('maxima_distancia', models.PositiveSmallIntegerField(choices=[('5', '5K'), ('10', '10K'), ('15', '15K'), ('21', '21K'), ('42', '42K'), ('50', '50K+')])),
                ('talla', models.CharField(choices=[('CH', 'CH'), ('M', 'M'), ('G', 'G'), ('XG', 'XG')], max_length=1)),
                ('confirmado', models.BooleanField()),
                ('the_end_2015', models.BooleanField()),
                ('the_end_2016', models.BooleanField()),
                ('the_end_2017', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_corredor_objects', to='registro.Club')),
            ],
            options={
                'verbose_name': 'corredor',
                'verbose_name_plural': 'corredores',
            },
        ),
        migrations.AlterUniqueTogether(
            name='club',
            unique_together={('nombre',)},
        ),
        migrations.AlterUniqueTogether(
            name='corredor',
            unique_together={('correo',)},
        ),
    ]
