# Generated by Django 2.1.3 on 2018-11-20 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['nombre'], 'verbose_name': 'club', 'verbose_name_plural': 'clubes'},
        ),
        migrations.AlterModelOptions(
            name='corredor',
            options={'ordering': ['nombre', 'club__nombre'], 'verbose_name': 'corredor', 'verbose_name_plural': 'corredores'},
        ),
    ]
