# Generated by Django 2.1.3 on 2018-11-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20181119_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corredor',
            name='maxima_distancia',
            field=models.PositiveSmallIntegerField(choices=[(5, '5K'), (10, '10K'), (15, '15K'), (21, '21K'), (42, '42K'), (50, '50K+')]),
        ),
    ]
