# Generated by Django 2.1.3 on 2018-11-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20181121_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corredor',
            name='talla',
            field=models.CharField(choices=[('CH', 'CH'), ('M', 'M'), ('G', 'G'), ('XG', 'XG')], max_length=2),
        ),
    ]
