# Generated by Django 2.1.3 on 2018-11-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_auto_20181121_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='corredor',
            name='playera',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corredor',
            name='tiempo_estimado_5K',
            field=models.PositiveSmallIntegerField(choices=[(1, '14 a 20 minutos'), (2, '21 a 29 minutos'), (3, '+30 minutos')], default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corredor',
            name='maxima_distancia',
            field=models.PositiveSmallIntegerField(choices=[(5, '5K'), (10, '10K'), (15, '15K'), (21, '21K'), (42, '42K'), (50, '+50K')]),
        ),
    ]
