# Generated by Django 2.1.3 on 2018-11-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_auto_20181122_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='corredor',
            name='playera_entregada',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corredor',
            name='confirmado',
            field=models.BooleanField(verbose_name='Acepto términos y condiciones'),
        ),
        migrations.AlterField(
            model_name='corredor',
            name='playera',
            field=models.BooleanField(verbose_name='Playera (opcional $150 MXP)'),
        ),
    ]
