# Generated by Django 2.1.3 on 2018-11-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_auto_20181122_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corredor',
            name='playera_entregada',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
