# Generated by Django 2.1.3 on 2018-12-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_auto_20181122_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='corredor',
            name='tiempo_objetivo_5K',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
