# Generated by Django 2.1.3 on 2019-01-06 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_corredor_tiempo_objetivo_5k'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corredor',
            old_name='playera_entregada',
            new_name='asistencia',
        ),
        migrations.RemoveField(
            model_name='corredor',
            name='tiempo_objetivo_5K',
        ),
    ]
