# Generated by Django 2.1.3 on 2019-11-28 06:00

from django.db import migrations, models
import ltrc.classes.manage_date


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_auto_20190106_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThenEnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(choices=[(2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=ltrc.classes.manage_date.get_current_year, verbose_name='año')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ThenEnd',
                'verbose_name_plural': 'ThenEnds',
            },
        ),
        migrations.RemoveField(
            model_name='corredor',
            name='maxima_distancia',
        ),
        migrations.RemoveField(
            model_name='corredor',
            name='originario_nuevo_laredo',
        ),
        migrations.RemoveField(
            model_name='corredor',
            name='playera',
        ),
        migrations.RemoveField(
            model_name='corredor',
            name='residente_nuevo_laredo',
        ),
        migrations.RemoveField(
            model_name='corredor',
            name='the_end_2015',
        ),
        migrations.RemoveField(
            model_name='corredor',
            name='the_end_2016',
        ),
        migrations.RemoveField(
            model_name='corredor',
            name='the_end_2017',
        ),
        migrations.RemoveField(
            model_name='corredor',
            name='tiempo_estimado_5K',
        ),
        migrations.AlterUniqueTogether(
            name='thenend',
            unique_together={('anio',)},
        ),
    ]
