# Generated by Django 2.1.3 on 2019-11-28 06:13

from django.db import migrations, models
import django.db.models.deletion
import ltrc.classes.manage_date


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0010_auto_20191128_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='corredor',
            name='the_end',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ThenEnd_corredor_objects', to='registro.ThenEnd'),
        ),
        migrations.AlterField(
            model_name='thenend',
            name='anio',
            field=models.IntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=ltrc.classes.manage_date.get_current_year, verbose_name='año'),
        ),
    ]
