# Generated by Django 2.1.3 on 2019-11-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0011_auto_20191128_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='corredor',
            name='folio',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='corredor',
            name='guia',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='corredor',
            unique_together={('correo', 'the_end')},
        ),
    ]
