# Generated by Django 2.1.3 on 2019-11-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0013_auto_20191128_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='corredor',
            name='colonia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='corredor',
            name='guia',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='corredor',
            name='talla',
            field=models.CharField(choices=[('CH', 'CH'), ('M', 'M'), ('G', 'G')], max_length=2),
        ),
    ]
